# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Jayanth
tagline:          'Discovering smart way of doing things'
description:      'This is my simple static website which shows that i am alive :P . Follow me on twitter <a href="https://twitter.com/jayanthsagar" target="_blank">@jayanthsagar</a>.'
url:              http://jayanthsagar.github.io
baseurl:          /

author:
  name:           'Jayanth sagar'
  url:            https://twitter.com/jayanthsagar

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jayanthsagar
