# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Jayanth
tagline:          'Discovering smart way of doing things'
description:      'This is my portfolio that showcases my best work, It also helps me refer to my previous work. Follow me <a href="https://twitter.com/jayanthsagar" target="_blank">@jayanthsagar</a>.'
url:              http://jayanthsagar.github.io
baseurl:          /

author:
  name:           'Jayanth sagar'
  url:            https://twitter.com/jayanthsagar

paginate:         1

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jayanthsagar
